import {
  FaFacebook,
  FaInstagram,
  FaYoutube,
  FaXTwitter,
  FaTiktok,
  FaPinterest,
  FaReddit,
  FaVimeo,
} from "react-icons/fa6";

export const PLATFORM_CONFIG = {
  facebook: {
    name: "Facebook",
    icon: FaFacebook,
    color: "#1877F2",
    placeholder: "Paste Facebook video, reel, or watch link...",
    description: "Download Facebook videos, reels, and stories.",
  },
  facebook_reels: {
    name: "Facebook Reels",
    icon: FaFacebook,
    color: "#1877F2",
    placeholder: "Paste Facebook Reel link...",
    description: "Download Facebook Reels in HD quality.",
  },
  instagram: {
    name: "Instagram",
    icon: FaInstagram,
    color: "#E4405F",
    placeholder: "Paste Instagram Reel, Post, or Story URL...",
    description: "Download Instagram reels, posts, and stories.",
  },
  youtube: {
    name: "YouTube",
    icon: FaYoutube,
    color: "#FF0000",
    placeholder: "Paste YouTube video, Shorts, or playlist URL...",
    description: "Download YouTube videos, Shorts, and music.",
  },
  x: {
    name: "X",
    icon: FaXTwitter,
    color: "#111827",
    placeholder: "Paste X video URL...",
    description: "Download videos from X (Twitter).",
  },
  tiktok: {
    name: "TikTok",
    icon: FaTiktok,
    color: "#000000",
    placeholder: "Paste TikTok video URL...",
    description: "Download TikTok videos without watermark.",
  },
  reddit: {
    name: "Reddit",
    icon: FaReddit,
    color: "#FF4500",
    placeholder: "Paste Reddit video URL...",
    description: "Download Reddit hosted videos.",
  },
  pinterest: {
    name: "Pinterest",
    icon: FaPinterest,
    color: "#E60023",
    placeholder: "Paste Pinterest Pin URL...",
    description: "Download Pinterest video pins.",
  },
  vimeo: {
    name: "Vimeo",
    icon: FaVimeo,
    color: "#00ADEF",
    placeholder: "Paste Vimeo video URL...",
    description: "Download Vimeo videos.",
  },
  dailymotion: {
    name: "Dailymotion",
    icon: null,
    color: "#0066DC",
    placeholder: "Paste Dailymotion video URL...",
    description: "Download Dailymotion videos.",
  },
  threads: {
    name: "Threads",
    icon: null,
    color: "#000000",
    placeholder: "Paste Threads post URL...",
    description: "Download videos from Threads.",
  },
  twitch: {
    name: "Twitch",
    icon: null,
    color: "#9146FF",
    placeholder: "Paste Twitch clip or VOD URL...",
    description: "Download Twitch clips and VODs.",
  },
  rumble: {
    name: "Rumble",
    icon: null,
    color: "#85C742",
    placeholder: "Paste Rumble video URL...",
    description: "Download Rumble videos.",
  },
  bilibili: {
    name: "Bilibili",
    icon: null,
    color: "#00A1D6",
    placeholder: "Paste Bilibili video URL...",
    description: "Download Bilibili videos.",
  },
  streamable: {
    name: "Streamable",
    icon: null,
    color: "#0B84FF",
    placeholder: "Paste Streamable video URL...",
    description: "Download Streamable videos.",
  },
  default: {
    name: "Cliply",
    icon: null,
    color: "#3B82F6",
    placeholder: "Paste any video URL from the internet...",
    description: "Download videos from 1000+ websites powered by yt-dlp.",
  },
};
